### ISSUE TITLE
Training can not start

### ISSUE THREAD

**Issue by glentimemaker** [you359/Keras-FasterRCNN#45]
Hi,
I'm using the gpu to run the train_frcnn.py. But it cannot start even at the beginning of epoch 1. 
When I kill the training, it always stop inside the line X, Y, img_data = next(data_gen_train), shown as below.
`Epoch 1/50
^CTraceback (most recent call last):
  File "train_frcnn.py", line 228, in <module>
    X, Y, img_data = next(data_gen_train)
  File "/home/newton/Keras-FasterRCNN/keras_frcnn/data_generators.py", line 309, in get_anchor_gt
    x_img = cv2.resize(x_img, (resized_width, resized_height), interpolation=cv2.INTER_CUBIC)
KeyboardInterrupt
`
Can anyone figure it out the reason? Thank you.

**Comment by william0418** [comment]
i have same problem!!!!!

it always run in def get_anchor_gt() 
the while loop in data_generators.py line 281 does not have break function

**Comment by miscla** [comment]
did u find solution?? i have same problem too

**Comment by collinarnett** [comment]
I fixed this issue in my pull request https://github.com/you359/Keras-FasterRCNN/pull/28/commits/ee4504b3b42b45d884ee4c2b9d69355149df3aba

**Comment by miscla** [comment]
> I fixed this issue in my pull request [ee4504b](https://github.com/you359/Keras-FasterRCNN/commit/ee4504b3b42b45d884ee4c2b9d69355149df3aba)

i already edit using your commit.. still the same.. iam only edit train_frcnn.py like your commit

**Comment by henryhudazhi** [comment]
maybe u can try this 
def get_img_output_length(width, height):
    def get_output_length(input_length):
        return input_length//16

**Comment by HYG-777** [comment]
> maybe u can try this
> def get_img_output_length(width, height):
> def get_output_length(input_length):
> return input_length//16

Thank you ,it works

**Comment by romain-rsr** [comment]
> maybe u can try this
> def get_img_output_length(width, height):
> def get_output_length(input_length):
> return input_length//16

Hi, where exactly did you add those lines in the code ? 

Thanks in advance

**Comment by henryhudazhi** [comment]
> > maybe u can try this
> > def get_img_output_length(width, height):
> > def get_output_length(input_length):
> > return input_length//16
> 
> Hi, where exactly did you add those lines in the code ?
> 
> Thanks in advance

just add a / in return input_length//16. 
The problem might because you cant get int using one /,using // you can get int.

**Comment by romain-rsr** [comment]
Hi, thank you for your quick answer, I added // instead of / in the get_output_length function of the vgg.py file, but I still get the same problem.

when checking what happens inside the function get_anchor_gt, I see that all_imgs list is empty, isn't it the problem here ?

I looked upstream in the code and this list is empty because when splitting the dataset into train / test (in train_frcnn.py), the code looks for strings that don't exist : 

> train_imgs = [s for s in all_imgs if s['imageset'] == 'trainval']
> test_imgs = [s for s in all_imgs if s['imageset'] == 'test']

(when checking the actual values for 'imageset' key among train_imgs dicts, I only find "train" or "val")

**Comment by giapbinhduong** [comment]
> Hi, thank you for your quick answer, I added // instead of / in the get_output_length function of the vgg.py file, but I still get the same problem.
> 
> when checking what happens inside the function get_anchor_gt, I see that all_imgs list is empty, isn't it the problem here ?
> 
> I looked upstream in the code and this list is empty because when splitting the dataset into train / test (in train_frcnn.py), the code looks for strings that don't exist :
> 
> > train_imgs = [s for s in all_imgs if s['imageset'] == 'trainval']
> > test_imgs = [s for s in all_imgs if s['imageset'] == 'test']
> 
> (when checking the actual values for 'imageset' key among train_imgs dicts, I only find "train" or "val")

Hello, could you tell me where is the python file to put "/"? I find it in many files but can't find it. Thank in advance!!!!
